#!/bin/bash

omni_path="/usr/lib/$1/omni.ja"
tmpdir=".omni.ja.tmpdir"

function tear_down()
{
    cd ..
    rm -rf $tmpdir
    exit $1
}

if [[ $# -eq 0 ]]; then
    echo "Must provide argument: firefox or thunderbird"
    exit 1
elif [[ "$1" != "firefox" && "$1" != "thunderbird" ]]; then
    echo "Must provide argument: 'firefox' or 'thunderbird'"
    exit 1
fi

if [[ ! -e "$omni_path" || ! -e platformHTMLBindings.xml || ! -e platformHTMLBindings.xml.mod ]]; then
    echo "File Missing! Exiting..."
    exit 1
fi

rm -rf $tmpdir
mkdir $tmpdir
    
sudo cp $omni_path $tmpdir
cd $tmpdir
unzip omni.ja
if [[ $? -ne 0 ]]; then
    echo "Failed to unzip. Exiting..."
    tear_down 1
fi

checknew=`diff chrome/toolkit/content/global/platformHTMLBindings.xml ../platformHTMLBindings.xml.mod`
exitcode="$?"
if [[ $exitcode -eq 0 ]]; then
    echo "Already updated!"
    tear_down 1
fi

res=`diff chrome/toolkit/content/global/platformHTMLBindings.xml ../platformHTMLBindings.xml`
exitcode="$?"
if [[ $exitcode -eq 2 ]]; then
    echo "Something wrong. Exiting..."
    tear_down 1
elif [[ $exitcode -eq 1 ]]; then
    echo "A diff of the files shows the following:"
    echo "$res"
    echo "Proceed anyway? [Y/N]"
    read ans
    if [[ "$ans" != "Y" ]]; then
        tear_down 0
    fi
fi

cp ../platformHTMLBindings.xml.mod chrome/toolkit/content/global/platformHTMLBindings.xml
sudo zip omni.ja chrome/toolkit/content/global/platformHTMLBindings.xml
echo "Copying to $omni_path"
sudo cp omni.ja $omni_path
tear_down 0
